/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c6a0f25aa7841e0531d5f199405fadcf)
interface __BaseEnv_Env {
	METRICS_CACHE: KVNamespace;
	TELEMETRY_DB: D1Database;
	LICENSE_DB: D1Database;
	ASSETS: Fetcher;
	SENDPULSE_API_ID: string;
	SENDPULSE_API_SECRET: string;
	PRO_MONTHLY_CHECKOUT_URL: "https://buy.stripe.com/test_fZu00bfXU4iufWJ5zWe7m00";
	PRO_YEARLY_CHECKOUT_URL: "https://buy.stripe.com/test_eVq7sD9zwaGS5i58M8e7m01";
	LICENSE_FROM_EMAIL: "licenses@atelier.ws";
	SITE_URL: "https://atelier.ws";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PRO_MONTHLY_CHECKOUT_URL" | "PRO_YEARLY_CHECKOUT_URL" | "LICENSE_FROM_EMAIL" | "SITE_URL">> {}
}
